### ISSUE TITLE
FlowDirection not working

### ISSUE THREAD

**Issue by ghost1372** [AndrewKeepCoding/WinUI3Localizer#17]
if we have a resource
somekey.FlowDirection | RightToLeft

and we set in Grid or any Element:

<Grid x:Localizer.Uid="somekey"

flow direction is not working but if we use x:Uid flow direction working fine.

**Comment by AndrewKeepCoding** [comment]
It doesn't work because the current version doesn't support enums.
This is one of the features I wanted to implement someday but I guess I can bring it up in the next version.

**Comment by AndrewKeepCoding** [comment]
Closed by #22.
