### ISSUE TITLE
multiple resources

### ISSUE THREAD

**Issue by ghost1372** [AndrewKeepCoding/WinUI3Localizer#18]
how to use for multiple resources?
for x:Uid we can use

`<TextBlock x:Uid="/ErrorMessages/PasswordTooWeak"/>
`

**Comment by AndrewKeepCoding** [comment]
Sorry @ghost1372.
[Factoring strings into multiple resources files](https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest#factoring-strings-into-multiple-resources-files) is not supported yet. Might be able to implement it in v2.

**Comment by Pietro228** [comment]
Would be cool to have. I currently need this feature

**Comment by AndrewKeepCoding** [comment]
@Pietro228 Yes. It'd be cool. I need to find some time to make this happen.

**Comment by AndrewKeepCoding** [comment]
Created a new issue #23 in the milestone for v2.0.0.
