### ISSUE TITLE
Localizing DLLs

### ISSUE THREAD

**Issue by Pietro228** [AndrewKeepCoding/WinUI3Localizer#19]
Hi,

is there any way how can I localize WinUI 3 library's page? 

I'm using my WinUI 3 library in my project that has a page with your localizer but it doesn't translate it when showed in my project.
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/00c1d3db-3260-402b-aee5-8d9a9804ee68)
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/2623b1ed-320a-473c-9981-1693c1223026)
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/801a7b45-cdeb-458f-b4f8-663349cea868)

Navigating to the page from my library:
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/15380603-56e7-489d-9c37-1cc06a09a3c7)

**Comment by AndrewKeepCoding** [comment]
Hi @Pietro228 !
The WinUI3Localizer works with controls in libraries. I actually created a class library with a `SettingsCard` and it worked. My first guess is that you have a separated "Strings" folder in your library project. In that case, you need to explicitly call `SetLanguage`, etc for that library

**Comment by Pietro228** [comment]
Came from a holiday and it suddenly started working LoL :D 

Anyway thank you for your willingness :)
