### ISSUE TITLE
Add support for factoring strings into multiple resources files

### ISSUE THREAD

**Issue by AndrewKeepCoding** [AndrewKeepCoding/WinUI3Localizer#23]
This is a [feature](https://learn.microsoft.com/en-us/windows/uwp/app-resources/localize-strings-ui-manifest#factoring-strings-into-multiple-resources-files) supported on the built-in localization.

**Comment by Pietro228** [comment]
How long will it take until it will be supported?

**Comment by AndrewKeepCoding** [comment]
TBH, I'm not sure. I need to find time for this. I'll do my best to make it happen as soon as possible, but I can't make any promises.

**Comment by Pietro228** [comment]
Hi, can you make it until the end of September? I need it for release of my app 😬

I'm not pressuring you, I just need to know what will be included in my app so that I can release it without localization for now.

**Comment by AndrewKeepCoding** [comment]
I think that's possible, but again, no promises. ⚠️
