### ISSUE TITLE
How to change language without restart the app?

### ISSUE THREAD

**Issue by sciencekiller** [AndrewKeepCoding/WinUI3Localizer#35]
I want to change the app's language without restart the app. Then I notice this library. I have already saw the sample app. But because I'm new in WinUI, so I didn't find the way to change the language in that sample app. Could any one please tell me the way to change the language? You can offer a document or give me a functhion. Any help are appreciated.

**Comment by AndrewKeepCoding** [comment]
Hi @sciencekiller!

You can get the entire code from this repo.
I'd recommend [cloning](https://carldesouza.com/clone-a-repository-from-github-in-visual-studio-2019-start-menu/) the repo and run the sample app so you can see how it's implemented.

Let me know if you need further help.

**Comment by AndrewKeepCoding** [comment]
I'm closing this but let me know if you have any questions.
