### ISSUE TITLE
Add support for attached properties

### ISSUE THREAD

**Issue by AndrewKeepCoding** [AndrewKeepCoding/WinUI3Localizer#36]
Based on a [question](https://stackoverflow.com/questions/77339384/how-can-i-localize-tooltipservice-tooltip-in-winui3) on StackOverflow.

Should be able to localize strings for attached properties like `ToolTipService.ToolTip`.

**Comment by sciencekiller** [comment]
I noticed that you have changed the tag to "enhancement". Was it meant this problem has been fixed? Or when will it be fixed?

**Comment by AndrewKeepCoding** [comment]
I labeled this to "enhancement" just because it was more like a not supported feature than a bug. I might be able to make time this weekend for this but no promises.

**Comment by AndrewKeepCoding** [comment]
@sciencekiller Just shipped as v2.1.0. Let me know if you have any feedback.
