### ISSUE TITLE
ILocalizer not found, with warning icon over the nuget package

### ISSUE THREAD

**Issue by DexrnZacAttack** [AndrewKeepCoding/WinUI3Localizer#51]
Using the sample provided in the readme, I get an error on StringsFolderPath, ILocalizer, and LocalizerBuilder...
```
Severity	Code	Description	Project	File	Line	Suppression State	Details
Error (active)	CS0118	'StringsFolderPath' is a variable but is used like a type	App		App.xaml.cs	41		
Error (active)	CS0246	The type or namespace name 'ILocalizer' could not be found (are you missing a using directive or an assembly reference?)	App		App.xaml.cs	44		
Error (active)	CS0246	The type or namespace name 'LocalizerBuilder' could not be found (are you missing a using directive or an assembly reference?)	App	App.xaml.cs	44		
```

I am using .NET 8, and I am quite new to C#... so maybe I'm doing something wrong?

**Comment by AndrewKeepCoding** [comment]
Hi @DexrnZacAttack!
It should work.
Can you post your code in App.xaml.cs?

**Comment by DexrnZacAttack** [comment]
> Hi @DexrnZacAttack! It should work. Can you post your code in App.xaml.cs?

Hmm in the nuget area it shows it having a warning icon, and when looking at the package details I see dependancies for .NET 6 and 7, that's why I figured that could be the issue... I'm using .NET 8 with 26100 SDK.
![Dexrn_devenv_I1Cly6HT3n_09-27-2024_02_00_43_641_PM](https://github.com/user-attachments/assets/42a4b93f-b82a-481e-9041-3c70f654613b)
![Dexrn_devenv_CjusKdBoHY_09-27-2024_02_01_17_125_PM](https://github.com/user-attachments/assets/1f901fec-6edc-4b3a-9bb0-70c7decb7c1c)



```cs
using Microsoft.UI.Xaml;
using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using Windows.Storage;

namespace WD.UI
{
    public partial class App : Application
    {
        private async Task InitializeLocalizer()
        {
            // Initialize a "Strings" folder in the executables folder.
            StringsFolderPath StringsFolderPath = Path.Combine(AppContext.BaseDirectory, "Strings");
            StorageFolder stringsFolder = await StorageFolder.GetFolderFromPathAsync(StringsFolderPath);

            ILocalizer localizer = await new LocalizerBuilder()
                .AddStringResourcesFolderForLanguageDictionaries(StringsFolderPath)
                .SetOptions(options =>
                {
                    options.DefaultLanguage = "en-US";
                })
                .Build();
        }

        public App()
        {
            InitializeComponent();
        }

        protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
            MainWindow.Activate();
        }
    }
}

```

**Comment by AndrewKeepCoding** [comment]
Add a `string` property for **StringsFolderPath**:

```cs
public static string StringsFolderPath { get; private set; } = string.Empty;
```

then change this line:

```cs
//StringsFolderPath StringsFolderPath = Path.Combine(AppContext.BaseDirectory, "Strings");
StringsFolderPath = Path.Combine(AppContext.BaseDirectory, "Strings");
```

You also need to add the **WinUI3Localizer** namespace:

```cs
using Microsoft.UI.Xaml;
using System;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Threading.Tasks;
using Windows.Storage;
using WinUI3Localizer:  // Add this line.
```

**Comment by DexrnZacAttack** [comment]
> Add a `string` property for **StringsFolderPath**:
> 
> ```cs
> public static string StringsFolderPath { get; private set; } = string.Empty;
> ```
> 
> then change this line:
> 
> ```cs
> //StringsFolderPath StringsFolderPath = Path.Combine(AppContext.BaseDirectory, "Strings");
> StringsFolderPath = Path.Combine(AppContext.BaseDirectory, "Strings");
> ```
> 
> You also need to add the **WinUI3Localizer** namespace:
> 
> ```cs
> using Microsoft.UI.Xaml;
> using System;
> using System.Diagnostics;
> using System.IO;
> using System.Reflection;
> using System.Threading.Tasks;
> using Windows.Storage;
> using WinUI3Localizer:  // Add this line.
> ```

It can't find that import...
```The type or namespace name 'WinUI3Localizer' could not be found (are you missing a using directive or an assembly reference?)```

**Comment by DexrnZacAttack** [comment]
Update: Setting it to .NET 7 makes it work, unfortunately I cannot use .NET 7 for this project.

**Comment by AndrewKeepCoding** [comment]
I just created a .NET 8 test app project and it works.
Can you share how your *.csproj file code?

Here is how the test app project file looks like:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>WinUIApp4</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <PublishProfile>win-$(Platform).pubxml</PublishProfile>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <Nullable>enable</Nullable>
    <WindowsSdkPackageVersion>10.0.19041.38</WindowsSdkPackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240829007" />
    <PackageReference Include="WinUI3Localizer" Version="2.2.0" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>

...

</Project>
```

**Comment by DexrnZacAttack** [comment]
> I just created a .NET 8 test app project and it works. Can you share how your *.csproj file code?
> 
> Here is how the test app project file looks like:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk">
>   <PropertyGroup>
>     <OutputType>WinExe</OutputType>
>     <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
>     <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
>     <RootNamespace>WinUIApp4</RootNamespace>
>     <ApplicationManifest>app.manifest</ApplicationManifest>
>     <Platforms>x86;x64;ARM64</Platforms>
>     <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
>     <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
>     <PublishProfile>win-$(Platform).pubxml</PublishProfile>
>     <UseWinUI>true</UseWinUI>
>     <EnableMsixTooling>true</EnableMsixTooling>
>     <Nullable>enable</Nullable>
>     <WindowsSdkPackageVersion>10.0.19041.38</WindowsSdkPackageVersion>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
>     <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240829007" />
>     <PackageReference Include="WinUI3Localizer" Version="2.2.0" />
>     <Manifest Include="$(ApplicationManifest)" />
>   </ItemGroup>
> 
> ...
> 
> </Project>
> ```

Here's mine:

```xml
<Project Sdk="Microsoft.NET.Sdk">
<PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>Test</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Platforms>x86;x64;ARM64</Platforms>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>True</UseWinUI>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
	<IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    <XamlDebuggingInformation>True</XamlDebuggingInformation>
    <DisableXbfLineInfo>False</DisableXbfLineInfo>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
	<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
	<Version>0.0.4</Version>
	<AssemblyVersion>$(Version)</AssemblyVersion>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.240829007" />
    <PackageReference Include="WinUI3Localizer" Version="2.2.0" />
    <Manifest Include="$(ApplicationManifest)" />
  </ItemGroup>
  </Project>
  ```
  
  I assume it's due to the 10.0.26100.0 SDK being used?

**Comment by AndrewKeepCoding** [comment]
I updated my csproj with your values and works.🤔

Maybe one of these helps:
- Delete the **bin** folder and the **obj** folder.
- [Unload Project] and [Reload Project with Dependencies].

Also see the issue is reproducible on a new WinUI 3 app.

**Comment by DexrnZacAttack** [comment]
> I updated my csproj with your values and works.🤔
> 
> Maybe one of these helps:
> 
>     * Delete the **bin** folder and the **obj** folder.
> 
>     * [Unload Project] and [Reload Project with Dependencies].
> 
> 
> Also see the issue is reproducible on a new WinUI 3 app.

Guess that worked... dunno why I had such an issue with it lol, thanks!

**Comment by DexrnZacAttack** [comment]
(updated title for others who have the same issue)

**Comment by AndrewKeepCoding** [comment]
Happens sometimes. I hope you enjoy the localizer.🙂

**Comment by DexrnZacAttack** [comment]
> Happens sometimes. I hope you enjoy the localizer.🙂

Hope so too! Can't seem to figure it out yet though.
