### ISSUE TITLE
Not working in Release mode.

### ISSUE THREAD

**Issue by lhson0606** [AndrewKeepCoding/WinUI3Localizer#52]
Hello, I am having a bug: the library works on Debug mode but it doens't show any text in Release mode. Link to my project : [here](https://github.com/korrotta/OneLastSong/tree/developing-main-layout) (developing-main-layout branch). Please have a look. There are two attached images, the first one is in Release mode and the second one is in Debug mode. Have a good day!
![image](https://github.com/user-attachments/assets/15130aab-01c3-4487-9dd3-04a799f6cbb7)
![image](https://github.com/user-attachments/assets/6b914996-226e-4ff6-8614-ef48f91b6b43)

**Comment by AndrewKeepCoding** [comment]
Hi @lhson0606 !
The WinUI3Localizer has issues with trimming. Can you try disabling trimming on your *.pubxml file?

```xml
<PublishTrimmed Condition="'$(Configuration)' != 'Debug'">False</PublishTrimmed>
```

**Comment by lhson0606** [comment]
It worked. Thank you a lot for your help! I'm closing the issue.
