### ISSUE TITLE
Example for Language Change

### ISSUE THREAD

**Issue by AntonioNusco** [AndrewKeepCoding/WinUI3Localizer#6]
I implemented everything correctly and the text changes according to the initial value of the language. Now I should make the app change the language in runtime on clicking a MenuFlyoutItem, could I have an example? the app is packaged and not built with TemplateStudio

**Comment by AntonioNusco** [comment]
ok, i solved doind this

In the Page.xaml.cs
`private void selectLanguage(object sender, RoutedEventArgs e)
		{
			App.localizer.SetLanguage("en-US");
		}`
		
And in the App.xaml.cs i have changed this
`public static ILocalizer localizer { get; set; }
localizer = await new LocalizerBuilder()
				.AddStringResourcesFolderForLanguageDictionaries(stringsFolder.Path)
				.SetOptions(options =>
				{
					options.DefaultLanguage = "it-IT";
					options.UseUidWhenLocalizedStringNotFound = true;
				})
				.Build();`

**Comment by AndrewKeepCoding** [comment]
Great! Let me know if you have any other question.😁
