### ISSUE TITLE
Can't change language

### ISSUE THREAD

**Issue by Pietro228** [AndrewKeepCoding/WinUI3Localizer#8]
Hi,

I want to use this plugin for my unpackaged app, but I found out that I can't change the language.

When I initialize localizer with different default language it throws me this error:
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/fd9e74f2-337c-445f-a518-0d20a580a1bf)

When I initialize it with the same language (for example "en-US") the SetLanguage(localization); method doesn't change the language at all when ran outside of VS.

Initialization:
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/88c527a6-25af-4fb4-9b0d-f5cd31a6f556)
Settings language (it really get the correct localization string, but doesn't change it when ran outside of VS):
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/790eb0c8-3327-4881-b69d-889ea862c4b7)

Am I doing it wrong? I would appreciate any help :)

**Comment by AndrewKeepCoding** [comment]
Hi @Pietro228!

You get this exception when the localizer can't find the language from its dictionaries.
Since it seems that this is a *packaged* app, my first guess is that the target Resources.resw file's *Build Action* is not set to *Content*. I should mention this in the README.

![image](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/80524586/50185788-0fed-46b5-bfb0-c33ec13e3ec9)

**Comment by Pietro228** [comment]
It's already set to Content and it's an unpackaged app.

I think that there's problem with the unpackaged app being started as a new process using "Process.Start(...);" from a packaged app.

**Comment by AndrewKeepCoding** [comment]
Can you confirm these?

- Does it work when you run your app by double-clicking the EXE file?
- Is the "String" folder and its contents, language folders and Resources.resw files , on the same folder where the EXE file is?

**Comment by Pietro228** [comment]
So I found a solution - for some reason `ApplicationLanguages.PrimaryLanguageOverride` return only first half of the language tag (I set "cs-CZ", but it returns "cs").

When I hardcode the "cs-CZ" tag, it works without any problems. Now I need to find a way how to get current language with the full tag.

**Comment by Pietro228** [comment]
I can't find a way how to get the full tag because it looks like your library doesn't support the "half tags" :/

**Comment by AndrewKeepCoding** [comment]
WinUI3Localizer uses tags as part of the path to get Resources.resw files. Changing the folders name inside the "Strings" folder should work.

For example,
    Strings\cs-CZ\Resources.resw
    to
    Strings\cs\Resources.resw

**Comment by Pietro228** [comment]
It only fixes the issue when run it using my application.

When I run it unpackaged (which I want to do to test it before uploading to my application) it still throws that exception. I guess that I have to wait for Microsoft to implement to get rid of it :D

I have a last question:
How do I set default language? In Windows it's a blank string, but it doesn't work with your library :/

**Comment by AndrewKeepCoding** [comment]
> When I run it unpackaged (which I want to do to test it before uploading to my application) it still throws that exception. 

Weird. It should work...🤔 At least works in my environment.

> When I run it unpackaged (which I want to do to test it before uploading to my application) it still throws that exception. 

You can set the default language when you build the localizer:

```cs
ILocalizer localizer = await new LocalizerBuilder()
    .AddStringResourcesFolderForLanguageDictionaries(StringsFolderPath)
    .SetOptions(options =>
        {
            // This needs to match the folder name in the "Strings" folder.
            options.DefaultLanguage = "en-US"; 
        })
    .Build();
```

**Comment by Pietro228** [comment]
> Weird. It should work...🤔 At least works in my environment.

I'll try it one more time.

> You can the default language when you build the localizer:

I know this, but how do I get system language to set it as default?

**Comment by AndrewKeepCoding** [comment]
Try the [CultureInfo](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo?view=net-7.0):

```cs
CultureInfo installedUICulture = CultureInfo.InstalledUICulture;
```

**Comment by Pietro228** [comment]
Already tried it. It returns the full culture string but now I have "cs". If I get it back to "cs-CZ", it will throw an exception because of the `ApplicationLanguages.PrimaryLanguageOverride` "cs" language tag.

I guess that I'll have to use your library in my main application as well.

**Comment by AndrewKeepCoding** [comment]
I've meaning to ask you why do you need `ApplicationLanguages.PrimaryLanguageOverride`? The WinUI3Localizer works without it.

**Comment by Pietro228** [comment]
Wanted to use the native system because it's easier. Now I'm sticking to your lib.

I have another issue - your localizer doesn't localize my strings in packaged app. It copies all files, sets the right language to the parameters but then displays default content set in XAML:
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/8022bd84-26b2-4cd4-8903-451e8638bd5a)

### This is my code:
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/edbacb3d-4b97-4b77-8467-a3fa19edfed6)
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/66713dc6-6687-4a57-a3b6-72fe60e09693)
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/9b6dceec-001d-4577-b4db-62f6b5f1ba36)
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/3f09fcfe-cc33-4ef2-8901-807ce519823f)
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/4e9db460-6201-44f4-b160-11bad0c16edb)
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/d3371aea-8528-4964-b237-2c8ad49a782c)

**Comment by AndrewKeepCoding** [comment]
Is this issue for the entire app? or a part of the app?

What happens if you change the language? Still doesn't work?

Can you also check if the localizer actually has a dictionary for 'cs-CZ' and it includes Uids (ex: "MainWindow_Dashboard") for your `NavigationViewItems` ?

You can get the dictionary after you build the localizer:

```cs
LanguageDictionary? dictionary = localizer
    .GetLanguageDictionaries()
    .FirstOrDefault(x => x.Language is "cs-CZ");
```

**Comment by Pietro228** [comment]
It's for the whole app and changing the language doesn't help :/

Checked it and it does contain it:
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/39548ef9-4bc2-4ce7-ad73-80c5c4ef789e)

**Comment by AndrewKeepCoding** [comment]
I can't reproduce your issue. Can you share your project (or create a minimal reproducible project) on GitHub?

**Comment by Pietro228** [comment]
It works for me in a new project :/ Can we have a call on Discord so I can show you my project? My Discord is: pietro.santa

**Comment by Pietro228** [comment]
Got it fixed! Thank you for your help :)

Had to put it before the window initialization.
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/9f85e309-9de6-430d-ac6b-3894560be5f8)

**Comment by Pietro228** [comment]
Found one small issue - On the app start it just localizes controls that don't have their text set in XAML.
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/92b33031-8eec-4f3f-b457-92f5ca9a6d5b)

Other controls that have set their content to "Account" don't change until I change language settings.
![obrazek](https://github.com/AndrewKeepCoding/WinUI3Localizer/assets/53868994/66585d36-ea07-4c06-9b64-4c5f71b0eaaf)

**Comment by Pietro228** [comment]
Okay, got it fixed as well :D I just set the language using `Localizer.Get().SetLanguage(...);` after creating the window instance.

I appreciate you willingness to help me! It's a great library :)

**Comment by Pietro228** [comment]
It sadly didn't fix it everywhere :D I just need to remove the content to make it work properly and it's really annoying to not see the original text in the editor.

**Comment by AndrewKeepCoding** [comment]
Just send you a DM on your Discord. 😁
But since we're on totally different time zones, are shared project that reproduces the issues might be a better option. Your case might require be a case that the localizer doesn't support, and I might need to modify the localizer.

**Comment by AndrewKeepCoding** [comment]
Based on your additional info on Discord, I finally reproduced your issue. The key was to set default values. For example:

```xaml
<TextBlock
    Text="This is the default text."
    l:Uids.Uid="SomeTextBlock" />
```

In this case, the `TextBox` is actually localized when you build the localizer but when the `TextBox` is loaded the default `Text` overrides the localized text.

In the next version of the WinUI3Localizer, I guess I might be able to add an option that runs a spot localization every time a control is loaded. Meanwhile, you need to workaround this by not setting default values or by calling `SetLanguage` when the `Page` that includes the target control is loaded.
