### ISSUE TITLE
How to use this package for projects conststing of multiple DLLs resp. code projects?

### ISSUE THREAD

**Issue by MichaelJachan** [AndrewKeepCoding/WinUI3Localizer#9]
Please give me a MWE for my SLN, which has an EXE PRJ and several DLL PRJs. Ecah DLL shall have its own resw-Files! 

Thank you

**Comment by AndrewKeepCoding** [comment]
Hi @MichaelJachan!

Can you create and share a GitHub repo with a minimal solution with the projects that you want to use the WinUI3Localizer for?

**Comment by AndrewKeepCoding** [comment]
I'm closing this but let me know if you have any questions.
